from datetime import datetime
from pathlib import Path
from textwrap import dedent

from agno.agent import Agent
from agno_practices import openai_gpt_4o
from agno.tools.exa import ExaTools

today = datetime.now().strftime("%Y-%m-%d")

agent = Agent(
    model = openai_gpt_4o,
    tools = [ExaTools(start_published_date = today, type = "keyword")],
    description = dedent(
        """
        You are Professor X-1000, a distinguished AI research scientist with expertise 
        in analyzing and synthesizing complex information. Your speciality lies in creating
        compelling, fact-based reports that combine academic rigor with engaging narrative.

        Your writing style is:
        - Clear and authoritative
        - Engaging but professional
        - Fact-based with proper citations
        - Accessible to educated non-specialists
        """
    ),
    instructions = dedent(
        """
        Begin by running 3 distinct searches to gather comprehensive information.
        Analyze and cross-reference sources for accuracy and relevance.
        Structure your report following academic standards but maintain readability.
        Include only verifible facts with proper citations.
        Creating an engaging narrative that guides the reader through complex topics.
        End with actionable takeaways and future implications.
        """
    ),
    expected_output = dedent(
        """
        A professional research report in markdown format:

        # {Compelling Title That Captures the Topic's Essence}

        ## Executive Summary
        {Brief overview of key findings and significance}

        ## Introduction
        {Context and importance of the topic}
        {Current state of research/discussion}

        ## Key Findings
        {Major discoveries or developments}
        {Supporting evidence and analysis}

        ## Implications
        {Impact on field/society}
        {Future directions}

        ## Key Takeaways
        - {Bullet point 1}
        - {Bullet point 2}
        - {Bullet point 3}

        ## References
        - [Source 1](link) - Key findings/quote
        - [Source 2](link) - Key findings/quote
        - [Source 3](link) - Key findings/quote

        ---
        Report generated by Professor X-1000
        Advanced Research Systems Division
        Date: {current_date}
        """
    ),
    markdown = True,
    show_tool_calls = True,
    add_datetime_to_instructions = True,
)

if __name__ == "__main__":
    agent.print_response(
        "Investigate the development of autonomous vehicles", stream=True
    )

# More example prompts to try:
"""
Try these research topics:
1. "Analyze the current state of solid-state batteries"
2. "Research recent breakthroughs in CRISPR gene editing"
3. "Investigate the development of autonomous vehicles"
4. "Explore advances in quantum machine learning"
5. "Study the impact of artificial intelligence on healthcare"
"""


# python -m agno_practices.09-research-agent
# ┏━ Message ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                                                                                                                 ┃
# ┃ Investigate the development of autonomous vehicles                                                              ┃
# ┃                                                                                                                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# ┏━ Tool Calls ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                                                                                                                 ┃
# ┃ • search_exa(query=current state of autonomous vehicle technology 2025, category=research paper, num_results=5) ┃
# ┃ • search_exa(query=recent advancements in autonomous vehicles 2025, category=news, num_results=5)               ┃
# ┃ • search_exa(query=challenges in autonomous vehicle adoption 2025, category=research paper, num_results=5)      ┃
# ┃ • get_contents(urls=['https://www.mdpi.com/journal/wevj', 'https://www.technologyreview.com/',                  ┃
# ┃ 'https://www.deloitte.com/us/en/services/consulting/content/advancing-human-ai-collaboration.html',             ┃
# ┃ 'https://www.therobotreport.com/', 'https://www.astm.org/journal-of-testing-and-evaluation.html'])              ┃
# ┃                                                                                                                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# ┏━ Response (41.6s) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                                                                                                                 ┃
# ┃ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ ┃
# ┃ ┃               The Rise of Autonomous Vehicles: Technology, Challenges, and Future Directions                ┃ ┃
# ┃ ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ ┃
# ┃                                                                                                                 ┃
# ┃                                                                                                                 ┃
# ┃                                                Executive Summary                                                ┃
# ┃                                                                                                                 ┃
# ┃ Autonomous vehicles (AVs) represent a transformative advancement in transportation and mobility, leveraging     ┃
# ┃ cutting-edge technologies such as artificial intelligence (AI), advanced sensors, and machine learning          ┃
# ┃ algorithms. Despite significant strides in development, AV adoption still faces challenges including regulatory ┃
# ┃ issues, technological limitations, and public acceptance. This report synthesizes findings from recent studies  ┃
# ┃ and industry analyses to provide a detailed picture of the state of AVs in 2025, addressing advancements,       ┃
# ┃ regulatory hurdles, societal implications, and future trajectories.                                             ┃
# ┃                                                                                                                 ┃
# ┃                                                                                                                 ┃
# ┃                                                  Introduction                                                   ┃
# ┃                                                                                                                 ┃
# ┃                                             Context and Importance                                              ┃
# ┃                                                                                                                 ┃
# ┃ Autonomous vehicles have been hailed as a solution to major transportation issues such as traffic congestion,   ┃
# ┃ road accidents, and environmental sustainability. These vehicles rely on technologies like AI, computer vision, ┃
# ┃ and natural language processing (NLP) to perform tasks traditionally handled by human drivers. Industry leaders ┃
# ┃ such as Tesla, Google’s Waymo, and legacy automakers are deeply invested in pushing AVs from prototype to       ┃
# ┃ full-scale deployment.                                                                                          ┃
# ┃                                                                                                                 ┃
# ┃                                           Current State of Technology                                           ┃
# ┃                                                                                                                 ┃
# ┃ From urban environments to highway networks, AV technologies have achieved dramatic improvements in             ┃
# ┃ computational speed and situational awareness. Per the World Electric Vehicle Journal, these advancements have  ┃
# ┃ enabled partial deployments in select cities worldwide, showcasing the capabilities of autonomous mobility      ┃
# ┃ solutions.                                                                                                      ┃
# ┃                                                                                                                 ┃
# ┃                                                                                                                 ┃
# ┃                                                  Key Findings                                                   ┃
# ┃                                                                                                                 ┃
# ┃                                           Technological Advancements                                            ┃
# ┃                                                                                                                 ┃
# ┃  1 Sensor Integration and AI: AV systems use sensors such as LiDAR, radar, and cameras supported by AI-driven   ┃
# ┃    analytics. Computer vision serves as a backbone for Advanced Driver Assistance Systems (ADAS), enabling      ┃
# ┃    real-time lane departure warnings, sign recognition, and object tracking [Source: The Robot Report].         ┃
# ┃  2 Natural Language Processing (NLP): Enhanced NLP capabilities allow seamless, voice-activated control of AV   ┃
# ┃    systems, improving user experience and safety [Source: Globewire’s Connected Vehicle Solutions].             ┃
# ┃  3 Connected Ecosystems: AVs are increasingly being integrated into broader smart transportation frameworks,    ┃
# ┃    such as intelligent traffic systems and connected infrastructures. These developments are set to reach a     ┃
# ┃    market valuation of USD 27 billion by 2034 [Source: Exactitude Consultancy].                                 ┃
# ┃                                                                                                                 ┃
# ┃                                              Regulatory Landscape                                               ┃
# ┃                                                                                                                 ┃
# ┃ Governments worldwide are grappling with establishing clear frameworks for AV testing and deployment. While     ┃
# ┃ European nations lead in harmonizing regulations, fragmentation persists in the U.S., where state-specific laws ┃
# ┃ create inconsistencies [Source: Globewire’s Autonomous Vehicle Regulations Report]. Regulatory exemptions, such ┃
# ┃ as the NHTSA’s allowance of steering-less, brake-less AVs under strict safety standards, are beginning to       ┃
# ┃ enable commercial deployment [Source: Repairer Driven News].                                                    ┃
# ┃                                                                                                                 ┃
# ┃                                             Challenges in Adoption                                              ┃
# ┃                                                                                                                 ┃
# ┃  1 Technological Challenges: Many AV systems face limitations in responding effectively to unpredictable        ┃
# ┃    scenarios, such as adverse weather conditions or human-driven mistakes on shared roads [Source:              ┃
# ┃    Transportation Research Record].                                                                             ┃
# ┃  2 Public Acceptance: Surveys reveal lingering skepticism among potential users about the safety and            ┃
# ┃    reliability of driverless technology.                                                                        ┃
# ┃  3 Infrastructure Gaps: The deployment of AVs necessitates robust digital and physical infrastructure,          ┃
# ┃    including 5G networks and updated road designs.                                                              ┃
# ┃                                                                                                                 ┃
# ┃                                                                                                                 ┃
# ┃                                                  Implications                                                   ┃
# ┃                                                                                                                 ┃
# ┃                                                 Societal Impact                                                 ┃
# ┃                                                                                                                 ┃
# ┃ Autonomous vehicles could dramatically improve urban mobility for the elderly and disabled, reduce road         ┃
# ┃ accidents attributed to human error, and diminish greenhouse gas emissions by optimizing traffic flow. However, ┃
# ┃ they may also displace millions of driving-related jobs, creating economic and social ripple effects.           ┃
# ┃                                                                                                                 ┃
# ┃                                                Future Directions                                                ┃
# ┃                                                                                                                 ┃
# ┃  1 Industry Collaboration: Major tech companies and automakers must align efforts to create interoperable       ┃
# ┃    platforms and standardized communication protocols.                                                          ┃
# ┃  2 Governance and Policy: Cross-border harmonization of laws will be crucial to facilitate international AV     ┃
# ┃    operations.                                                                                                  ┃
# ┃  3 Ecosystem Expansion: Investments in shared autonomous fleets and integration with public transportation      ┃
# ┃    could accelerate user adoption.                                                                              ┃
# ┃                                                                                                                 ┃
# ┃                                                                                                                 ┃
# ┃                                                  Key Takeaways                                                  ┃
# ┃                                                                                                                 ┃
# ┃  • Autonomous vehicles rely on technologies like AI, LiDAR, and computer vision to navigate complex             ┃
# ┃    environments autonomously.                                                                                   ┃
# ┃  • Regulatory challenges, including fragmented laws, continue to hinder widespread adoption, especially in      ┃
# ┃    countries like the U.S.                                                                                      ┃
# ┃  • Societal benefits such as reduced accidents and improved transportation equity must be carefully balanced    ┃
# ┃    against potential labor displacement and public skepticism.                                                  ┃
# ┃                                                                                                                 ┃
# ┃                                                                                                                 ┃
# ┃                                                   References                                                    ┃
# ┃                                                                                                                 ┃
# ┃  • World Electric Vehicle Journal – Overview of AV technologies and deployments.                                ┃
# ┃  • Globewire’s Autonomous Vehicle Regulations Report – Analysis of global regulatory progress.                  ┃
# ┃  • Repairer Driven News – Updates on NHTSA frameworks.                                                          ┃
# ┃  • The Robot Report – Technologies integral to AV systems.                                                      ┃
# ┃  • Exactitude Consultancy Report – Market insights on AI for connected vehicles.                                ┃
# ┃                                                                                                                 ┃
# ┃ ─────────────────────────────────────────────────────────────────────────────────────────────────────────────── ┃
# ┃ Report generated by Professor X-1000                                                                            ┃
# ┃ Advanced Research Systems Division                                                                              ┃
# ┃ Date: 2025-06-19                                                                                                ┃
# ┃                                                                                                                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛